version: '3.7'
# networks:
#   static-network:
#     ipam:
#       config:
#         - subnet: 172.23.0.0/16


#########################################
# Services communicating in the backend #
#########################################

services:
  central-api:
    build: ./backend/central-api
    ports:
      - 8000:8000

  summary-api:
    build: ./backend/summary-api
    ports:
      - 8001:8001

  frontend:
    image: static-web-page
    build: ./frontend
    ports:
      - 8002:8002